In [ ]:

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import StandardScaler

from google.colab import drive
drive.mount('/content/drive')
path = '/content/Titanic-Dataset.csv'
df = pd.read_csv(path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df.head(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C


In [ ]:
# ============================================
# TITANIC SURVIVAL PREDICTION USING TENSORFLOW
# ============================================

# ============================================
# IMPORT LIBRARIES
# ============================================

import pandas as pd
import numpy as np
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

print("\nFIRST 5 ROWS")
print(df.head())

# ============================================
# SELECT REQUIRED FEATURES
# ============================================

# Input Features
X = df[['Pclass', 'Age', 'Fare']]

# Target
y = df['Survived']

# Fill missing Age values with mean
X['Age'] = X['Age'].fillna(X['Age'].mean())

# ============================================
# NORMALIZATION
# ============================================

# Min-Max Scaling
scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X)

print("\nNORMALIZED FEATURES")
print(X_scaled[:5])

# ============================================
# TRAIN TEST SPLIT
# ============================================

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

# ============================================
# CREATE NEURAL NETWORK
# ============================================

model = tf.keras.Sequential([

    # Hidden Layer
    tf.keras.layers.Dense(
        units=2,
        activation='sigmoid',
        input_shape=(3,)
    ),

    # Output Layer
    tf.keras.layers.Dense(
        units=1,
        activation='sigmoid'
    )

])


model.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.1),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# ============================================
# MODEL SUMMARY
# ============================================

print("\nMODEL SUMMARY")
model.summary()

# ============================================
# TRAIN MODEL
# ============================================

history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.1
)


loss, accuracy = model.evaluate(X_test, y_test)

print("\nTEST LOSS:", loss)
print("TEST ACCURACY:", accuracy)

# ============================================
# MAKE PREDICTIONS
# ============================================

predictions = model.predict(X_test)

print("\nPREDICTIONS")
print(predictions[:10])

# ============================================
# CONVERT PROBABILITIES TO 0/1
# ============================================

predicted_classes = (predictions > 0.5).astype(int)

print("\nPREDICTED CLASSES")
print(predicted_classes[:10])

# ============================================
# TEST WITH CUSTOM INPUT
# ============================================

# Example:
# Pclass = 1
# Age = 24
# Fare = 120

custom_input = np.array([[1, 24, 120]])

# Normalize using same scaler
custom_input_scaled = scaler.transform(custom_input)

prediction = model.predict(custom_input_scaled)

print("\nCUSTOM PASSENGER PREDICTION")
print(prediction)

if prediction[0][0] > 0.5:
    print("SURVIVED")
else:
    print("NOT SURVIVED")

# ============================================
# DISPLAY FINAL WEIGHTS
# ============================================

print("\nFINAL WEIGHTS")

for layer in model.layers:

    weights, biases = layer.get_weights()

    print("\nWEIGHTS:")
    print(weights)

    print("\nBIASES:")
    print(biases)

# ============================================
# END
# ============================================


FIRST 5 ROWS
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN

/tmp/ipykernel_2699/920151248.py:34: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Age'] = X['Age'].fillna(X['Age'].mean())
/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 2)              │             8 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11 (44.00 B)

 Trainable params: 11 (44.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6187 - loss: 0.6688 - val_accuracy: 0.6944 - val_loss: 0.6262
Epoch 2/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6156 - loss: 0.6616 - val_accuracy: 0.6944 - val_loss: 0.6201
Epoch 3/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6156 - loss: 0.6604 - val_accuracy: 0.6944 - val_loss: 0.6154
Epoch 4/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6156 - loss: 0.6586 - val_accuracy: 0.6944 - val_loss: 0.6095
Epoch 5/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6156 - loss: 0.6582 - val_accuracy: 0.6944 - val_loss: 0.6147
Epoch 6/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6156 - loss: 0.6564 - val_accuracy: 0.6944 - val_loss: 0.6088
Epoch 7/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6156 - loss: 0.6553 - val_accuracy: 0.6944 - val_loss: 0.6181
Epoch 8/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6156 - loss: 0.6548 - val_accuracy: 0.6944 - v

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

PREDICTIONS
[[0.24211271]
 [0.42729172]
 [0.26477078]
 [0.5246679 ]
 [0.28149572]
 [0.6454773 ]
 [0.24116251]
 [0.2769769 ]
 [0.2754114 ]
 [0.65415055]]

PREDICTED CLASSES
[[0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step

CUSTOM PASSENGER PREDICTION
[[0.65477765]]
SURVIVED

FINAL WEIGHTS

WEIGHTS:
[[ 2.3224587   0.11457584]
 [ 1.4894947   1.0405991 ]
 [-0.5164699  -0.63525313]]

BIASES:
[-1.8727686   0.07045945]

WEIGHTS:
[[-3.1958199 ]
 [-0.18904537]]

BIASES:
[1.3038926]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [ ]:
# ============================================
# SAVE MODEL
# ============================================

model.save("titanic_ann_model.keras")

print("Model Saved Successfully")

Model Saved Successfully


In [ ]:
from google.colab import files

files.download("titanic_ann_model.keras")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>